### ISSUE TITLE
[BUG] python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by flurmind** [linuxserver/docker-calibre-web#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After I deployed stack in portainer I have a bug in log:
_python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory_

I try to search this lyb, lyb is present:
_dpkg -S libc.so.6
libc6:amd64: /lib/x86_64-linux-gnu/libm.so.6_

### Steps To Reproduce

Deploy stack in portainer editor

### Environment

```markdown
- OS:Debian 11
- How docker service was installed: distro's packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
Created in portainer>stack>editor
```

### Container logs

```bash
Setting up libxcb-sync1:amd64 (1.14-3ubuntu3) ...
Setting up xz-utils (5.2.5-2ubuntu1) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lzma.1.gz because associated file /usr/share/man/man1/xz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/unlzma.1.gz because associated file /usr/share/man/man1/unxz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcat.1.gz because associated file /usr/share/man/man1/xzcat.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzmore.1.gz because associated file /usr/share/man/man1/xzmore.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzless.1.gz because associated file /usr/share/man/man1/xzless.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzdiff.1.gz because associated file /usr/share/man/man1/xzdiff.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcmp.1.gz because associated file /usr/share/man/man1/xzcmp.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzgrep.1.gz because associated file /usr/share/man/man1/xzgrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzegrep.1.gz because associated file /usr/share/man/man1/xzegrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzfgrep.1.gz because associated file /usr/share/man/man1/xzfgrep.1.gz (of link group lzma) doesn't exist
Setting up libsensors5:amd64 (1:3.6.0-7ubuntu1) ...
Setting up libglapi-mesa:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libxcb-dri2-0:amd64 (1.14-3ubuntu3) ...
Setting up libxshmfence1:amd64 (1.3-1build4) ...
Setting up libllvm15:amd64 (1:15.0.6-3~ubuntu0.22.04.2) ...
Setting up libdrm-common (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libelf1:amd64 (0.186-1build1) ...
Setting up libxkbcommon0:amd64 (1.4.0-1) ...
Setting up libwayland-client0:amd64 (1.20.0-1ubuntu0.1) ...
Setting up libdrm2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-amdgpu1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libdrm-nouveau2:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libgbm1:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libdrm-radeon1:amd64 (2.4.113-2~ubuntu0.22.04.1) ...
Setting up libgl1-mesa-dri:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libegl-mesa0:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libegl1:amd64 (1.4.0-1) ...
Setting up libglx-mesa0:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Setting up libglx0:amd64 (1.4.0-1) ...
Setting up libgl1:amd64 (1.4.0-1) ...
Setting up libgl1-mesa-glx:amd64 (22.2.5-0ubuntu0.1~22.04.1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
**** Installing/updating calibre ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  1  129M    1 1796k    0     0   857k      0  0:02:34  0:00:02  0:02:32 1889k
  3  129M    3 4372k    0     0  1412k      0  0:01:33  0:00:03  0:01:30 2242k
  5  129M    5 7156k    0     0  1747k      0  0:01:15  0:00:04  0:01:11 2426k
  7  129M    7 10.0M    0     0  2010k      0  0:01:06  0:00:05  0:01:01 2593k
 10  129M   10 13.3M    0     0  2234k      0  0:00:59  0:00:06  0:00:53 2751k
 13  129M   13 16.8M    0     0  2433k      0  0:00:54  0:00:07  0:00:47 3094k
 15  129M   15 20.7M    0     0  2619k      0  0:00:50  0:00:08  0:00:42 3366k
 19  129M   19 24.8M    0     0  2795k      0  0:00:47  0:00:09  0:00:38 3654k
 22  129M   22 29.2M    0     0  2965k      0  0:00:44  0:00:10  0:00:34 3939k
 26  129M   26 33.9M    0     0  3131k      0  0:00:42  0:00:11  0:00:31 4224k
 30  129M   30 39.1M    0     0  3317k      0  0:00:40  0:00:12  0:00:28 4572k
 35  129M   35 45.8M    0     0  3583k      0  0:00:37  0:00:13  0:00:24 5145k
 41  129M   41 54.3M    0     0  3951k      0  0:00:33  0:00:14  0:00:19 6054k
 48  129M   48 63.3M    0     0  4299k      0  0:00:30  0:00:15  0:00:15 6991k
 55  129M   55 72.0M    0     0  4584k      0  0:00:28  0:00:16  0:00:12 7811k
 62  129M   62 81.5M    0     0  4884k      0  0:00:27  0:00:17  0:00:10 8675k
 70  129M   70 91.8M    0     0  5194k      0  0:00:25  0:00:18  0:00:07 9414k
 77  129M   77  100M    0     0  5396k      0  0:00:24  0:00:19  0:00:05 9468k
 83  129M   83  108M    0     0  5544k      0  0:00:23  0:00:20  0:00:03 9302k
 90  129M   90  117M    0     0  5700k      0  0:00:23  0:00:21  0:00:02 9292k
 97  129M   97  126M    0     0  5854k      0  0:00:22  0:00:22 --:--:-- 9167k
100  129M  100  129M    0     0  5909k      0  0:00:22  0:00:22 --:--:-- 8871k
Creating symlinks...
	Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
	Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
	Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
	Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
	Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
	Symlinking /app/calibre/web2disk to /usr/bin/web2disk
	Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
	Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
	Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
	Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
	Symlinking /app/calibre/calibredb to /usr/bin/calibredb
	Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
	Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
	Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
	Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
	Symlinking /app/calibre/calibre to /usr/bin/calibre
	Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
	Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
	Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/
Setting up desktop integration...
____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________
	Traceback (most recent call last):
	  File "calibre/linux.py", line 858, in setup_desktop_integration
	  File "calibre/linux.py", line 880, in do_setup_desktop_integration
	  File "calibre/linux.py", line 911, in install_xdg_junk
	  File "calibre/linux.py", line 896, in install_icons
	  File "calibre/linux.py", line 890, in install_single_icon
	  File "subprocess.py", line 364, in check_call
	  File "subprocess.py", line 345, in call
	  File "subprocess.py", line 966, in __init__
	  File "subprocess.py", line 1842, in _execute_child
	FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'
Creating un-installer: /usr/bin/calibre-uninstall
There were 1 warnings
* Setting up desktop integration failed with error:
[custom-init] No custom files found, skipping...
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
```

**Comment by drizuid** [comment]
are you able to reproduce this issue when not using portainer and using the official repo for docker rather than your package manager? none of us here are able to reproduce this.

Note that we do not support or recommend deploying containers with portainer due to the high number of issues it causes for non-experts.

**Comment by drizuid** [comment]
> Hi, i have exactly the same issue.

I'm confused.. did you compare your container logs to the OPs? You say you have the "exact same issue" but your logs look fine and you have no libm errors...

**Comment by vcdwelt** [comment]
> > Hi, i have exactly the same issue.
> 
> I'm confused.. did you compare your container logs to the OPs? You say you have the "exact same issue" but your logs look fine and you have no libm errors...

See Linuxserver Thread, you're right not exactly the same issue, overlooked the part with libm.so, only focused on the desktop integration part.

Sorry

**Comment by Athanor66** [comment]
Good morning.
I have a similar issue on a Terramaster NAS.
This is the log:

```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/mods:universal-calibre files to container
[mod-init] linuxserver/mods:universal-calibre at sha256:8740df3342812152e5fa06fce2eff629189a91dfe2f8037e272b982cbabc5e8c has been previously applied skipping
[migrations] started
[migrations] no migrations found
groupmod: existing lock file /etc/group.lock without a PID
groupmod: cannot lock /etc/group; try again later.
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1011
User gid:    1011
-------------------------------------
**** Adding calibre dependencies to package install list ****
[mod-init] **** Installing all mod packages ****
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-security/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package xz-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Unable to locate package libopengl0
E: Unable to locate package libxkbcommon0
E: Unable to locate package libegl1
E: Unable to locate package libxdamage1
E: Unable to locate package libgl1-mesa-glx
E: Package 'xz-utils' has no installation candidate
**** Installing/updating calibre ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  8  130M    8 11.6M    0     0  13.1M      0  0:00:09 --:--:--  0:00:09 13.1M
 63  130M   63 83.7M    0     0  44.4M      0  0:00:02  0:00:01  0:00:01 72.1M
100  130M  100  130M    0     0  52.6M      0  0:00:02  0:00:02 --:--:-- 74.3M
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/etc/s6-overlay/s6-rc.d/init-mod-universal-calibre-setup/run: line 59: /app/calibre/calibre_postinstall: No such file or directory
[custom-init] No custom files found, skipping...
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
python3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory
```

Can you help me to address a solution?
Thank you

**Comment by Athanor66** [comment]
[RESOLVED]

It seems that I have resolved the problrm updating the docker image with these commands:
Update the image: **docker pull lscr.io/linuxserver/calibre-web:latest**
Stop the running container: **docker stop calibre-webRiviste**
Delete the container: **docker rm calibre-webRiviste**
and then reinstalling with:```

docker run -d \
  --name=calibre-webRiviste \
  -e PUID=1011 \
  -e PGID=1011 \
  -e TZ=Europe/Rome \
  -e DOCKER_MODS=linuxserver/mods:universal-calibre `#optional` \
  -e OAUTHLIB_RELAX_TOKEN_SCOPE=1 `#optional` \
  -p 8089:8083 \
  -v /Volume2/BIBLIOTECHE/RIVISTE:/riviste \
  -v /Volume2/CalibreDBRiviste:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/calibre-web:latest
```

The log has again some strange error, but Calibre web is accessible and works:


```
**** Adding calibre dependencies to package install list ****
[mod-init] **** Installing all mod packages ****
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-security/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package xz-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Unable to locate package libopengl0
E: Unable to locate package libxkbcommon0
E: Unable to locate package libegl1
E: Unable to locate package libxdamage1
E: Unable to locate package libgl1-mesa-glx
E: Package 'xz-utils' has no installation candidate
**** Installing/updating calibre ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  130M    0 17781    0     0  22113      0  1:43:26 --:--:--  1:43:26 22113
 21  130M   21 28.6M    0     0  15.9M      0  0:00:08  0:00:01  0:00:07 28.7M
 49  130M   49 65.0M    0     0  23.1M      0  0:00:05  0:00:02  0:00:03 32.4M
 78  130M   78  102M    0     0  27.0M      0  0:00:04  0:00:03  0:00:01 34.2M
100  130M  100  130M    0     0  28.7M      0  0:00:04  0:00:04 --:--:-- 34.9M
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/etc/s6-overlay/s6-rc.d/init-mod-universal-calibre-setup/run: line 59: /app/calibre/calibre_postinstall: No such file or directory
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by drizuid** [comment]
it's not really resolved, your docker host has a dns issue `Temporary failure resolving 'archive.ubuntu.com'` which is preventing your container from looking up URLs. that is the cause of your errors. Unfortunately, we do not test or support terramaster nas units.

**Comment by Athanor66** [comment]
Yes, it is very unfortunate that we cannot have your support.
I'll try to solve it on my own.
Thanks anyway.

**Comment by drizuid** [comment]
closing this as the OP has never replied and all these other people have a different setups and different issues.
